### ISSUE TITLE
python 3.4 - surely not

### ISSUE THREAD

**Issue by samuelcolvin** [samuelcolvin/aiohttp-devtools#1]
Does this package need to support python 3.4?

I would suggest not. 3.5 is in wide usage and is available on all major platforms I've seen.

Also keeping support for 3.4 would make the code (both the library and the generated `start` project) significantly uglier.

@asvetlov ?

**Comment by asvetlov** [comment]
@samuelcolvin agreed.
Feel free to don't care about 3.4.
