### ISSUE TITLE
No module named 'aiohttp_devtools.runserver'

### ISSUE THREAD

**Issue by FraBle** [samuelcolvin/aiohttp-devtools#4]
Trace:
```
>> adev runserver server.py make_app
Traceback (most recent call last):
  File "/Users/<user>/.virtualenvs/<project>/bin/adev", line 7, in <module>
    from aiohttp_devtools.cli import cli
  File "/Users/<user>/.virtualenvs/<project>/lib/python3.5/site-packages/aiohttp_devtools/cli.py", line 3, in <module>
    from .runserver.logs import setup_logging
ImportError: No module named 'aiohttp_devtools.runserver'
```

**Comment by samuelcolvin** [comment]
Thanks for reporting this. I had been running aiohttp-devtools myself after installing with `pip install -e .` so  hadn't noticed I'd forgotten to update `packages` in setup.py.

I've fixed this and started work on tests, while they're not complete they should prevent something like this going wrong again.

**Comment by FraBle** [comment]
No problem at all! I'm looking forward to use this tool for our projects! Did you update pypi as well?

**Comment by samuelcolvin** [comment]
Just updated pypi now.
